language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
script:
  # - coverage run runserver.py
  - pytest --cov
after_success:
  - coveralls
